= Tanuki
:nofooter:

Tanuki is a numerical library in {cpp}11 built on top of
link:https://arma.sourceforge.net/[Armadillo] as a need for the MPI
parallelization of several numerical algorithms to be employed in
high-performance computing (HPC). It implements all the numerical methods
described in the link:https://eprints.soton.ac.uk/467576/[thesis] by the
author. Tanuki parallelizes the following algorithms using hybrid MPI/OpenMP
programming and the shared memory facilities of
link:https://www.boost.org/doc/libs/1_83_0/doc/html/interprocess.html[Boost
Interprocess]:

* multiplication of many large matrices (using variadic template),
* Cholesky decomposition,
* forward and back substitution with triangular matrices,
* iterated Gram-Schmidt (with orthogonality ensured),
* weighted orthogonalization, and
* Givens relaxation scheme (GRS).

== Dependency

* link:https://arma.sourceforge.net/[Armadillo] (version 12.6)
* link:https://avro.apache.org/[Apache Avro] ({cpp}) (version 1.10)
* link:https://www.boost.org/[Boost] (`filesystem` and `system`) (version 1.82)
* link:https://cmake.org/[CMake] (version 3.14)
* MPI (tested with link:https://www.mpich.org/[MPICH] version 4.1)
* OpenMP

== Building

Compiler wrappers provided by the MPI implementation should be used. The
library directories of any dependencies not in the standard directories of the
operating system should be provided to the `-DCMAKE_INSTALL_RPATH` option of
the CMake command. At the root of the project directory,

----
mkdir build
cd build
cmake -G Ninja \
      -DCMAKE_C_COMPILER="mpicc;-cc=clang" \
      -DCMAKE_CXX_COMPILER="mpicxx;-cxx=clang++" \
      -DCMAKE_INSTALL_PREFIX=/opt/tanuki \
      -DCMAKE_INSTALL_RPATH=$LIBRARY_PATH \
      -DBUILD_TEST=ON \
      ..
ninja install
ctest
----

Make can be used by omitting the `-G Ninja` option and using `make install`
instead.

An all-inclusive header is at `include/tanuki.h`. Static and shared libraries
are under `lib`.

== Documentation

Documentation can be generated by

----
mkdir -p target/site/apidocs
doxygen
----

It is also available at https://hc1839.github.io/tanuki/apidocs/.
